### ISSUE TITLE
Hover effect over button 

### ISSUE THREAD

**Issue by sbanati** [Rafflafressia/bamboo-lyric-search-app#22]
This might be a tacky idea but what if we have a hover effect on the search button. Ill let my lead designer advise on this. I think its easy anyone can code this but just in terms of design is this something that would enhance the design or does it make it look MID af ?

**Comment by Rafflafressia** [comment]
Added the hover effect to the main button - will push shortly.

**Comment by Rafflafressia** [comment]
Added
